version: "3.9"

volumes:
  openplc-data:
  sqlite-db:

services:

  flaskendpoint:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - type: volume
        source: sqlite-db
        target: /flaskEndPoint/app/db

  openplc:
    build: https://github.com/thiagoralves/OpenPLC_v3.git
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: openplc-data
        target: /OpenPLC_v3/webserver
